// Teste: fotos de perfil nas Conversas. Rodar: node tests/e2e/avatar.e2e.mjs
import { chromium } from "playwright";
import fs from "node:fs";
import assert from "node:assert/strict";
const ext = new URL("../..", import.meta.url).pathname.replace(/\/$/, "");
const here = new URL(".", import.meta.url).pathname;
const shots = process.env.SHOTS || here + ".shots";
fs.mkdirSync(shots, { recursive: true });
const profile = here + ".profile-avatar";
fs.rmSync(profile, { recursive: true, force: true });
const ctx = await chromium.launchPersistentContext(profile, { channel: "chromium", headless: true, viewport: { width: 1440, height: 860 }, args: [`--disable-extensions-except=${ext}`, `--load-extension=${ext}`] });
await ctx.route("https://web.whatsapp.com/**", (r) => r.fulfill({ contentType: "text/html", body: fs.readFileSync(here + "fake-whatsapp.html", "utf8") }));
let [sw] = ctx.serviceWorkers();
if (!sw) sw = await ctx.waitForEvent("serviceworker");
const id = sw.url().split("/")[2];
const errors = [];
const wa = await ctx.newPage();
await wa.goto("https://web.whatsapp.com/");
const page = await ctx.newPage();
page.on("pageerror", (e) => errors.push(e.message));
await page.goto(`chrome-extension://${id}/conversas.html`);
await page.waitForSelector(".status.ready", { timeout: 15000 });
const shown = () => page.evaluate(() => Object.fromEntries([...document.querySelectorAll(".item")].map((i) => { const img = i.querySelector(".avimg"); return [i.querySelector(".name").textContent, img && img.complete && img.naturalWidth > 0 ? img.src.slice(0, 30) : img ? "carregando/erro" : "iniciais"]; })));
await page.waitForFunction(() => [...document.querySelectorAll(".item .avimg")].filter((i) => i.complete && i.naturalWidth > 0).length >= 2, null, { timeout: 15000 });
const list = await shown();
console.log("lista:", list);
assert.match(list["John Smith"], /^data:image/);
assert.match(list["Carla Souza"], /^data:image/, "link expirado trocado por um novo");
assert.equal(list["Anna"], "iniciais");
console.log("pedidos de foto ao WhatsApp:", await wa.evaluate(() => window.__picCalls));
await page.click(".item >> text=John Smith");
await page.waitForSelector(".thead .avimg");
await page.waitForSelector(".side .top .avimg");
console.log("cabeçalho e painel com foto: ok");
await page.screenshot({ path: shots + "/fotos.png" });
// recarregar não pede as fotos de novo (cache de 1 dia)
const before = (await wa.evaluate(() => window.__picCalls)).length;
await page.reload();
await page.waitForSelector(".item .avimg");
await page.waitForTimeout(2000);
const after = (await wa.evaluate(() => window.__picCalls)).length;
console.log("pedidos novos ao recarregar:", after - before);
assert.equal(after - before, 0);
console.log("ERRORS", errors);
assert.equal(errors.length, 0);
await ctx.close();
console.log("FOTOS OK");
