// Teste: tela cheia só do chat (Conversas). Rodar: node tests/e2e/fullscreen.e2e.mjs
import { chromium } from "playwright";
import fs from "node:fs";
import assert from "node:assert/strict";
const ext = new URL("../..", import.meta.url).pathname.replace(/\/$/, "");
const here = new URL(".", import.meta.url).pathname;
const shots = process.env.SHOTS || here + ".shots";
fs.mkdirSync(shots, { recursive: true });
const profile = here + ".profile-full";
fs.rmSync(profile, { recursive: true, force: true });
const ctx = await chromium.launchPersistentContext(profile, { channel: "chromium", headless: true, viewport: { width: 1440, height: 860 }, args: [`--disable-extensions-except=${ext}`, `--load-extension=${ext}`] });
await ctx.route("https://web.whatsapp.com/**", (r) => r.fulfill({ contentType: "text/html", body: fs.readFileSync(here + "fake-whatsapp.html", "utf8") }));
let [sw] = ctx.serviceWorkers();
if (!sw) sw = await ctx.waitForEvent("serviceworker");
const id = sw.url().split("/")[2];
const errors = [];
const dash = await ctx.newPage();
dash.on("pageerror", (e) => errors.push(e.message));
const wa = await ctx.newPage();
await wa.goto("https://web.whatsapp.com/");
await dash.bringToFront();
await dash.goto(`chrome-extension://${id}/dashboard.html#/conversas`);
const frame = await (await dash.waitForSelector('iframe[title="Conversas"]')).contentFrame();
await frame.waitForSelector(".status.ready", { timeout: 15000 });
console.log("iframe allow:", await dash.getAttribute('iframe[title="Conversas"]', "allow"), "| allowfullscreen:", await dash.getAttribute('iframe[title="Conversas"]', "allowfullscreen"));
await frame.click(".item >> text=John Smith");
await frame.waitForSelector(".b");
await frame.click("#fullBtn");
await frame.waitForFunction(() => Boolean(document.fullscreenElement));
await dash.waitForTimeout(600);
const box = await frame.evaluate(() => { const r = document.querySelector(".app").getBoundingClientRect(); return { w: Math.round(r.width), h: Math.round(r.height), top: Math.round(r.top), vw: innerWidth, vh: innerHeight, label: document.getElementById("fullBtn").getAttribute("aria-label") }; });
console.log("em tela cheia:", box);
assert.equal(box.top, 0);
assert.equal(box.h, box.vh, "o chat ocupa a altura toda");
assert.equal(box.w, box.vw, "o chat ocupa a largura toda");
await dash.screenshot({ path: shots + "/tela-cheia.png" });
// digitar continua funcionando em tela cheia
await frame.fill("#text", "Teste em tela cheia");
await frame.click("#fullBtn");
await frame.waitForFunction(() => !document.fullscreenElement);
console.log("saiu da tela cheia:", await frame.getAttribute("#fullBtn", "aria-label"), "| texto mantido:", await frame.inputValue("#text"));
console.log("ERRORS", errors);
assert.equal(errors.length, 0);
await ctx.close();
console.log("TELA CHEIA OK");
