// Teste: ligar/desligar as Conversas em Opções → Módulos. Rodar: node tests/e2e/module-toggle.e2e.mjs
import { chromium } from "playwright";
import fs from "node:fs";
import assert from "node:assert/strict";
const ext = new URL("../..", import.meta.url).pathname.replace(/\/$/, "");
const here = new URL(".", import.meta.url).pathname;
const profile = here + ".profile-mod";
fs.rmSync(profile, { recursive: true, force: true });
const ctx = await chromium.launchPersistentContext(profile, { channel: "chromium", headless: true, viewport: { width: 1300, height: 800 }, args: [`--disable-extensions-except=${ext}`, `--load-extension=${ext}`] });
await ctx.route("https://web.whatsapp.com/**", (r) => r.fulfill({ contentType: "text/html", body: fs.readFileSync(here + "fake-whatsapp.html", "utf8") }));
let [sw] = ctx.serviceWorkers();
if (!sw) sw = await ctx.waitForEvent("serviceworker");
const id = sw.url().split("/")[2];
const errors = [];
const opts = await ctx.newPage();
opts.on("pageerror", (e) => errors.push(e.message));
await opts.goto(`chrome-extension://${id}/options.html`);
await opts.waitForSelector("#mod-conversas");
console.log("padrão ligado:", await opts.isChecked("#mod-conversas"));
assert.equal(await opts.isChecked("#mod-conversas"), true);
const dash = await ctx.newPage();
dash.on("pageerror", (e) => errors.push(e.message));
await dash.goto(`chrome-extension://${id}/dashboard.html#/`);
await dash.waitForSelector("aside nav button");
const menu = () => dash.locator("aside nav button").allInnerTexts();
console.log("menu ligado:", await menu());
assert.ok((await menu()).includes("Conversas"));
// desligar
await opts.bringToFront();
await opts.uncheck("#mod-conversas");
await opts.waitForSelector("#modStatus.ok");
await dash.bringToFront();
await dash.waitForFunction(() => ![...document.querySelectorAll("aside nav button")].some((b) => b.textContent.trim() === "Conversas"), null, { timeout: 5000 });
console.log("menu desligado:", await menu());
const wa = await ctx.newPage();
await wa.goto("https://web.whatsapp.com/");
await wa.waitForTimeout(4000);
const r = await dash.evaluate(() => chrome.runtime.sendMessage({ channel: "orbita:chat", op: "chat.list" }));
const chats = await dash.evaluate(() => new Promise((res) => { const q = indexedDB.open("orbita-chat"); q.onsuccess = () => { const g = q.result.transaction("chats").objectStore("chats").count(); g.onsuccess = () => res(g.result); }; q.onerror = () => res(-1); }));
console.log("desligado → pedido:", r.error, "| conversas gravadas:", chats);
assert.equal(r.ok, false);
assert.equal(chats, 0, "nada foi sincronizado com o módulo desligado");
await dash.goto(`chrome-extension://${id}/conversas.html`);
console.log("tela:", (await dash.locator(".welcome").innerText()).replace(/\s+/g, " "));
// religar → sincroniza
await opts.bringToFront();
await opts.check("#mod-conversas");
await dash.bringToFront();
await dash.waitForSelector(".item", { timeout: 15000 });
console.log("religado:", await dash.locator(".item .name").allInnerTexts());
console.log("ERRORS", errors);
assert.equal(errors.length, 0);
await ctx.close();
console.log("MÓDULO OK");
